services: 
  app:
    build:
      context: .
    environment:
      - LOKI_URL=http://loki:3100
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./app.db}
    ports:
      - "8000:8000"
    depends_on:
      - loki
    networks:
      - loki-net
  grafana:
    image: grafana/grafana:latest
    ports: 
      - '3000:3000'
    networks: 
      - loki-net

  loki:
    image: grafana/loki:latest
    ports: 
      - '3100:3100'
    networks: 
      - loki-net
      
  database: 
    image: db_hakaton
    build:
      context: .
    ports:
      - "8080:8080"
    networks: 
      - loki-net
    depends_on:
      - grafana
      - loki
    
networks:
  loki-net:
    driver: bridge


